### ISSUE TITLE
Vaccination rates as an S-curve instead of linear speedup?

### ISSUE THREAD

**Issue by quad** [chrisjbillington/chrisjbillington.github.io#5]
https://github.com/chrisjbillington/chrisjbillington.github.io/blob/12d973829b91e7f49053186f40495c38f1a9f6f3/vic-2021.py#L242-L247

Vaccination curves taper off. Would an S-curve or a log curve be more accurate?

**Comment by chrisjbillington** [comment]
Definitely, but this is intended as a short-term projection, the final level of vaccine coverage doesn't affect the outcome very much on the timescales I'm interested in, so I think I'll leave this bit simple and just cutting off sharply, despite not being realistic.

Of course if we see a slowdown in vaccine uptake soon, then it'll be an issue, but I don't expect a slowdown until we're well past e.g. 80% of adults vaccinated. If we start to see a slowdown before this modelling is made redundant, I'll adjust as needed.
